#!/bin/bash
source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo ">>>> Executing syncdb [and migrate]"
python "$OPENSHIFT_REPO_DIR"/manage.py syncdb --noinput
#python "$OPENSHIFT_REPO_DIR"/manage.py migrate --noinput

echo ">>>> Executing collectstatic"
python "$OPENSHIFT_REPO_DIR"/manage.py collectstatic --noinput

